
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./credentials.json
      - GOOGLE_CLOUD_PROJECT=cvfrog
      - GEMINI_API_KEY=${GEMINI_API_KEY}

    depends_on:
      - texlive

  texlive:
    image: kjarosh/latex:2024.4-minimal
    volumes:
      - ./texlive:/data
