FROM 	kjarosh/latex:2025.1

WORKDIR /app

RUN tlmgr update --self && \
    tlmgr install \
      collection-latexrecommended \
      collection-latexextra \
      collection-fontsrecommended \
      cmap \
      charter \
      fontawesome5 \
    && tlmgr install \
      hyperref \
      xcolor \
      titlesec \
      enumitem \
      paracol \
      lastpage \
      geometry \
      amsmath \
      eso-pic \
      bookmark \
      changepage \
      needspace \
      iftex \
    && mktexlsr
