version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - texlive

  texlive:
    image: kjarosh/latex:2024.4-minimal
    volumes:
      - ./texlive:/data
