
services:
  latex_compiler:
    build:
      context: .
      dockerfile: Dockerfile.tex
    working_dir: /app
    volumes:
      - ./:/app
    # Disable TTY to prevent interactive prompts in pdflatex
    tty: false